### ISSUE TITLE
run autoreconf -i, but report library used but 'RANLIB' is undefined

### ISSUE THREAD

**Issue by xuxiaoyang0527** [onomondo/onomondo-uicc#5]
Hi author，

When i run autoreconf -i, some undefined error report, below is details.

aclocal: warning: couldn't open directory 'm4': No such file or directory
src/softsim/crypto/Makefile.am:17: error: library used but 'RANLIB' is undefined
src/softsim/crypto/Makefile.am:17:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/softsim/crypto/Makefile.am:17:   to 'configure.ac' and run 'autoconf' again.
src/softsim/milenage/Makefile.am:18: error: library used but 'RANLIB' is undefined
src/softsim/milenage/Makefile.am:18:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/softsim/milenage/Makefile.am:18:   to 'configure.ac' and run 'autoconf' again.
src/softsim/uicc/Makefile.am:18: error: library used but 'RANLIB' is undefined
src/softsim/uicc/Makefile.am:18:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/softsim/uicc/Makefile.am:18:   to 'configure.ac' and run 'autoconf' again.
autoreconf: automake failed with exit status: 1

Please help check  this error.

Thanks.

**Comment by laf0rge** [comment]
sadly you don't provide us with any details whatsoever, like which kindof host operating system / version you are using.

ranlib is normally provided as part of the GNU toolchain / binutils.
