### ISSUE TITLE
Building 2.0.0 fails with unresolved references

### ISSUE THREAD

**Issue by sertys3** [onomondo/onomondo-uicc#8]
Trying to build on ubuntu with cmake fails miserably on two steps. The documented cmake command is invalid at first. It should be : 
cmake -S . -B build -DCONFIG_USE_SYSTEM_HEAP=y

Yet building with : cmake --build build  produces an undefined reference with : 
```[ 70%] Built target uicc
[ 76%] Built target storage
[ 90%] Built target crypto
[ 96%] Built target milenage
[ 98%] Linking C executable softsim
/usr/bin/ld: CMakeFiles/softsim.dir/main.c.o: in function `vpcd_rx':
main.c:(.text+0x72): undefined reference to `ss_logp'
/usr/bin/ld: main.c:(.text+0xcf): undefined reference to `ss_logp'
/usr/bin/ld: main.c:(.text+0x122): undefined reference to `ss_logp'
/usr/bin/ld: main.c:(.text+0x174): undefined reference to `ss_logp'
```

I can only guess this is related to how dependencies are described with the cmake lists.

Please advise,
Daniel

**Comment by roni1234321** [comment]
+1

**Comment by benjaminbruun** [comment]
Thank you for posting the observation here. I have updated the initial instructions of the readme file to include a config that actually builds.
A todo might be to do a base config that does not require the command line inputs. But at least you now know what is being chosen without anything happening automatically behind the scene.
